import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/ReduxProvider";
import NavigationBar from "./ui/navigationBar/NavBar";
import LowerNavigationBar from "./ui/navigationBar/LowerNavBar";
import { SessionProvider } from "next-auth/react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


const Layout = ({ children }: { children: React.ReactNode }) => {
    return (
      <div className="min-h-screen flex flex-col">
        {/* Fixed top nav */}
        <nav className="fixed top-0 left-0 right-0 h-16 z-50 bg-white">
          <NavigationBar />
        </nav>
  
        {/* Main content */}
        <main className="flex-1 overflow-y-auto bg-slate-300
          mt-16 mb-16"> {/* mt/mb should match nav heights */}
          {children}
        </main>
  
        {/* Fixed bottom nav */}
        <nav className="fixed bottom-0 left-0 right-0 h-16 z-50 bg-white">
          <LowerNavigationBar />
        </nav>
      </div>
    );
};



  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <ReduxProvider>
        <SessionProvider>
          <Layout>
            {children}
          </Layout>
        </SessionProvider>
      </ReduxProvider>
    </body>
  </html>
  );
}
